version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Test Dockerfile changes
          command: |
            set -x
            make build
