version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Test Dockerfile changes
          command: |
            set -x
            pushd awscli
            make build
